name: gmdsitut
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas>=2.0
  - numpy<2 
  - matplotlib 
  - openpyxl
  - xlrd
  - jupyter 
  - notebook 
  - scipy 
  - shapely
  - rtree
  - pyproj>=2.0
  - pyshp<=2.4.1
  - psutil
  - git
  - nbconvert
  - pip
  - pip:
       - flopy == 3.9.3
       - pyemu == 1.3.8
       - pypestutils == 0.3.0


